config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :attendees

      resources :comments

      resources :events

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "events#index"
  resources :attendees
  resources :comments
  resources :events
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Direct associations

  belongs_to :event

  belongs_to :commenter,
             class_name: "User"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    event.to_s
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::GraphitiController
  def index
    comments = CommentResource.all(params)
    respond_with(comments)
  end

  def show
    comment = CommentResource.find(params)
    respond_with(comment)
  end

  def create
    comment = CommentResource.build(params)

    if comment.save
      render jsonapi: comment, status: :created
    else
      render jsonapi_errors: comment
    end
  end

  def update
    comment = CommentResource.find(params)

    if comment.update_attributes
      render jsonapi: comment
    else
      render jsonapi_errors: comment
    end
  end

  def destroy
    comment = CommentResource.find(params)

    if comment.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: comment
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :current_user_must_be_comment_commenter,
                only: %i[edit update destroy]

  before_action :set_comment, only: %i[show edit update destroy]

  def index
    @q = Comment.ransack(params[:q])
    @comments = @q.result(distinct: true).includes(:commenter,
                                                   :event).page(params[:page]).per(10)
  end

  def show; end

  def new
    @comment = Comment.new
  end

  def edit; end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      message = "Comment was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @comment, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: "Comment was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    message = "Comment was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to comments_url, notice: message
    end
  end

  private

  def current_user_must_be_comment_commenter
    set_comment
    unless current_user == @comment.commenter
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:event_id, :commenter_id, :comment_text)
  end
end

app/views/comments/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Comment #<%= comment.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Event</dt>
      <dd>
        <% if @comment.event.present? %>
          <%= link_to comment.event, comment.event %>
        <% end %>
      </dd>

      <dt>Commenter</dt>
      <dd>
        <% if @comment.commenter.present? %>
          <%= link_to comment.commenter, comment.commenter %>
        <% end %>
      </dd>

      <dt>Comment text</dt>
      <dd><%= comment.comment_text %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back comment, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @comment.commenter %>
          <%= link_to edit_comment_url(comment), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @comment.commenter %>
          <%= link_to comment, method: :delete, data: { confirm: "Do you really want to delete this comment?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(comment.updated_at) %> ago
  </div>
</div>

app/views/comments/_comments_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "comments_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :comment_text_cont, "Comment text contains" %>
    <%= f.text_field :comment_text_cont, :class => "form-control", :placeholder => "Comment text contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :commenter_email_cont, "Commenter email contains" %>
    <%= f.text_field :commenter_email_cont, :class => "form-control", :placeholder => "Commenter email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :event_name_cont, "Event name contains" %>
    <%= f.text_field :event_name_cont, :class => "form-control", :placeholder => "Event name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/comments" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#comments_filters">
  Show filters
</a>

app/views/comments/_form.html.erb
<% was_validated = comment.errors.any? %>

<%= form_with(model: comment, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% event_class = "form-control" %>
    <% event_was_invalid = comment.errors.include?(:event) %>

    <% if was_validated %>
      <% if event_was_invalid %>
        <% event_class << " is-invalid" %>
      <% else %>
        <% event_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :event_id %>
    <%= f.collection_select :event_id, Event.all, :id, :to_s, {}, class: "form-control" %>
    <% if event_was_invalid %>
      <% comment.errors.full_messages_for(:event).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.hidden_field :commenter_id, value: current_user.id %>
  <div class="form-group">
    <% comment_text_class = "form-control" %>
    <% comment_text_was_invalid = comment.errors.include?(:comment_text) %>

    <% if was_validated %>
      <% if comment_text_was_invalid %>
        <% comment_text_class << " is-invalid" %>
      <% else %>
        <% comment_text_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :comment_text %>
    <%= f.text_area :comment_text, class: comment_text_class, placeholder: "Enter comment text" %>
    <% if comment_text_was_invalid %>
      <% comment.errors.full_messages_for(:comment_text).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/comments/_list_item.html.erb
<%= link_to comment, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= comment %>
    <small class="text-muted">
      <%= time_ago_in_words(comment.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/comments/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Comment #<%= @comment.id %>
      </h2>

      <div class="card-body">
        <%= render "form", comment: @comment %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Comments

      <%= link_to new_comment_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "comments/comments_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Comments

        <%= link_to new_comment_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @comments, partial: "list_item", as: :comment %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @comments, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/comments/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Comment
      </h2>

      <div class="card-body">
        <%= render "form", comment: @comment %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @comment, partial: "card", as: :comment %>
  </div>
</div>