config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :attendees

      resources :comments

      resources :events

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "events#index"
  resources :attendees
  resources :comments
  resources :events
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  # Direct associations

  belongs_to :event,
             counter_cache: true

  belongs_to :attendee,
             class_name: "User"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    event.to_s
  end
end

app/controllers/api/v1/attendees_controller.rb
class Api::V1::AttendeesController < Api::V1::GraphitiController
  def index
    attendees = AttendeeResource.all(params)
    respond_with(attendees)
  end

  def show
    attendee = AttendeeResource.find(params)
    respond_with(attendee)
  end

  def create
    attendee = AttendeeResource.build(params)

    if attendee.save
      render jsonapi: attendee, status: :created
    else
      render jsonapi_errors: attendee
    end
  end

  def update
    attendee = AttendeeResource.find(params)

    if attendee.update_attributes
      render jsonapi: attendee
    else
      render jsonapi_errors: attendee
    end
  end

  def destroy
    attendee = AttendeeResource.find(params)

    if attendee.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: attendee
    end
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :current_user_must_be_attendee_attendee,
                only: %i[edit update destroy]

  before_action :set_attendee, only: %i[show edit update destroy]

  def index
    @q = Attendee.ransack(params[:q])
    @attendees = @q.result(distinct: true).includes(:attendee,
                                                    :event).page(params[:page]).per(10)
  end

  def show; end

  def new
    @attendee = Attendee.new
  end

  def edit; end

  def create
    @attendee = Attendee.new(attendee_params)

    if @attendee.save
      message = "Attendee was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @attendee, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @attendee.update(attendee_params)
      redirect_to @attendee, notice: "Attendee was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @attendee.destroy
    message = "Attendee was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to attendees_url, notice: message
    end
  end

  private

  def current_user_must_be_attendee_attendee
    set_attendee
    unless current_user == @attendee.attendee
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_attendee
    @attendee = Attendee.find(params[:id])
  end

  def attendee_params
    params.require(:attendee).permit(:event_id, :attendee_id, :status)
  end
end

app/views/attendees/_attendees_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "attendees_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :status_cont, "Status contains" %>
    <%= f.text_field :status_cont, :class => "form-control", :placeholder => "Status contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :attendee_email_cont, "Attendee email contains" %>
    <%= f.text_field :attendee_email_cont, :class => "form-control", :placeholder => "Attendee email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :event_name_cont, "Event name contains" %>
    <%= f.text_field :event_name_cont, :class => "form-control", :placeholder => "Event name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/attendees" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#attendees_filters">
  Show filters
</a>

app/views/attendees/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Attendee #<%= attendee.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Event</dt>
      <dd>
        <% if @attendee.event.present? %>
          <%= link_to attendee.event, attendee.event %>
        <% end %>
      </dd>

      <dt>Attendee</dt>
      <dd>
        <% if @attendee.attendee.present? %>
          <%= link_to attendee.attendee, attendee.attendee %>
        <% end %>
      </dd>

      <dt>Status</dt>
      <dd><%= attendee.status %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back attendee, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @attendee.attendee %>
          <%= link_to edit_attendee_url(attendee), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @attendee.attendee %>
          <%= link_to attendee, method: :delete, data: { confirm: "Do you really want to delete this attendee?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(attendee.updated_at) %> ago
  </div>
</div>

app/views/attendees/_form.html.erb
<% was_validated = attendee.errors.any? %>

<%= form_with(model: attendee, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% event_class = "form-control" %>
    <% event_was_invalid = attendee.errors.include?(:event) %>

    <% if was_validated %>
      <% if event_was_invalid %>
        <% event_class << " is-invalid" %>
      <% else %>
        <% event_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :event_id %>
    <%= f.collection_select :event_id, Event.all, :id, :to_s, {}, class: "form-control" %>
    <% if event_was_invalid %>
      <% attendee.errors.full_messages_for(:event).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.hidden_field :attendee_id, value: current_user.id %>
  <div class="form-group">
    <% status_class = "form-control" %>
    <% status_was_invalid = attendee.errors.include?(:status) %>

    <% if was_validated %>
      <% if status_was_invalid %>
        <% status_class << " is-invalid" %>
      <% else %>
        <% status_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :status %>
    <%= f.text_field :status, class: status_class, placeholder: "Enter status" %>
    <% if status_was_invalid %>
      <% attendee.errors.full_messages_for(:status).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/attendees/_list_item.html.erb
<%= link_to attendee, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= attendee %>
    <small class="text-muted">
      <%= time_ago_in_words(attendee.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/attendees/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Attendee #<%= @attendee.id %>
      </h2>

      <div class="card-body">
        <%= render "form", attendee: @attendee %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/attendees/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Attendees

      <%= link_to new_attendee_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "attendees/attendees_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Attendees

        <%= link_to new_attendee_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @attendees, partial: "list_item", as: :attendee %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @attendees, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/attendees/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Attendee
      </h2>

      <div class="card-body">
        <%= render "form", attendee: @attendee %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/attendees/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @attendee, partial: "card", as: :attendee %>
  </div>
</div>