config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :attendees

      resources :comments

      resources :events

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "events#index"
  resources :attendees
  resources :comments
  resources :events
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  # Direct associations

  has_many   :attendees,
             dependent: :nullify

  has_many   :comments,
             dependent: :destroy

  belongs_to :host,
             class_name: "User"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::GraphitiController
  def index
    events = EventResource.all(params)
    respond_with(events)
  end

  def show
    event = EventResource.find(params)
    respond_with(event)
  end

  def create
    event = EventResource.build(params)

    if event.save
      render jsonapi: event, status: :created
    else
      render jsonapi_errors: event
    end
  end

  def update
    event = EventResource.find(params)

    if event.update_attributes
      render jsonapi: event
    else
      render jsonapi_errors: event
    end
  end

  def destroy
    event = EventResource.find(params)

    if event.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: event
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :current_user_must_be_event_host,
                only: %i[edit update destroy]

  before_action :set_event, only: %i[show edit update destroy]

  def index
    @q = Event.ransack(params[:q])
    @events = @q.result(distinct: true).includes(:host, :comments,
                                                 :attendees).page(params[:page]).per(10)
  end

  def show
    @attendee = Attendee.new
    @comment = Comment.new
  end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = Event.new(event_params)

    if @event.save
      message = "Event was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @event, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    message = "Event was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to events_url, notice: message
    end
  end

  private

  def current_user_must_be_event_host
    set_event
    unless current_user == @event.host
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :host_id, :start, :end, :address,
                                  :details, :photo)
  end
end

app/views/events/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Event #<%= event.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= event.name %></dd>

      <dt>Host</dt>
      <dd>
        <% if @event.host.present? %>
          <%= link_to event.host, event.host %>
        <% end %>
      </dd>

      <dt>Start</dt>
      <dd><%= event.start %></dd>

      <dt>End</dt>
      <dd><%= event.end %></dd>

      <dt>Address</dt>
      <dd><%= event.address %></dd>

      <dt>Details</dt>
      <dd><%= event.details %></dd>

      <dt>Photo</dt>
      <dd>
        <%= cl_image_tag @event.photo, class: "img-fluid" %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back event, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @event.host %>
          <%= link_to edit_event_url(event), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @event.host %>
          <%= link_to event, method: :delete, data: { confirm: "Do you really want to delete this event?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(event.updated_at) %> ago
  </div>
</div>

app/views/events/_event_attendees.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Attendees

    <a data-toggle="collapse" href="#event_attendees_new_form">
      Add attendee
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @event.attendees.each do |attendee| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to attendee, attendee %>

        <% if current_user == attendee.attendee %>
          <%= link_to attendee, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="event_attendees_new_form">
        <%= render partial: "events/event_attendees_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/events/_event_attendees_new_form.html.erb
<%= form_with(model: @attendee, local: true) do |f| %>

  <%= f.hidden_field :event_id, value: @event.id %>

  <%= f.hidden_field :attendee_id, value: current_user.id %>

  <div class="form-group">
    <%= f.label :status %>

    <%= f.text_field :status, class: "form-control" %>
  </div>

  <%= f.submit "Create attendee", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/events/_event_comments.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Comments

    <a data-toggle="collapse" href="#event_comments_new_form">
      Add comment
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @event.comments.each do |comment| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to comment, comment %>

        <% if current_user == comment.commenter %>
          <%= link_to comment, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="event_comments_new_form">
        <%= render partial: "events/event_comments_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/events/_event_comments_new_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>

  <%= f.hidden_field :event_id, value: @event.id %>

  <%= f.hidden_field :commenter_id, value: current_user.id %>

  <div class="form-group">
    <%= f.label :comment_text %>
    <%= f.text_area :comment_text, rows: "3", class: "form-control" %>
  </div>

  <%= f.submit "Create comment", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/events/_events_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "events_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :details_cont, "Details contains" %>
    <%= f.text_field :details_cont, :class => "form-control", :placeholder => "Details contains" %>
  </div>

  <div class="form-group">
    <%= f.label :address_cont, "Address contains" %>
    <%= f.text_field :address_cont, :class => "form-control", :placeholder => "Address contains" %>
  </div>

  <div class="form-group">
    <%= f.label :end_cont, "End contains" %>
    <%= f.text_field :end_cont, :class => "form-control", :placeholder => "End contains" %>
  </div>

  <div class="form-group">
    <%= f.label :start, "Start" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='startgteqPicker' data-target-input="nearest">
          <%= f.text_field :start_gteq, :class => "form-control datetimepicker-input", :placeholder => "Start greater than or equal to", :data => {:target => '#startgteqPicker'} %>
          <div class="input-group-append" data-target='#startgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='startlteqPicker' data-target-input="nearest">
          <%= f.text_field :start_lteq, :class => "form-control datetimepicker-input", :placeholder => "Start less than or equal to", :data => {:target => '#startlteqPicker'} %>
          <div class="input-group-append" data-target='#startlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#startgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#startlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#startgteqPicker').on("dp.change", function (e) {
              $('#startlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#startlteqPicker').on("dp.change", function (e) {
              $('#startgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :host_email_cont, "Host email contains" %>
    <%= f.text_field :host_email_cont, :class => "form-control", :placeholder => "Host email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/events" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#events_filters">
  Show filters
</a>

app/views/events/_form.html.erb
<% was_validated = event.errors.any? %>

<%= form_with(model: event, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = event.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% event.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.hidden_field :host_id, value: current_user.id %>
  <div class="form-group">
    <% start_class = "form-control" %>
    <% start_was_invalid = event.errors.include?(:start) %>

    <% if was_validated %>
      <% if start_was_invalid %>
        <% start_class << " is-invalid" %>
      <% else %>
        <% start_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :start %>
    <%= f.datetime_select :start, class: start_class, placeholder: "Enter start" %>
    <% if start_was_invalid %>
      <% event.errors.full_messages_for(:start).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% end_class = "form-control" %>
    <% end_was_invalid = event.errors.include?(:end) %>

    <% if was_validated %>
      <% if end_was_invalid %>
        <% end_class << " is-invalid" %>
      <% else %>
        <% end_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :end %>
    <%= f.text_field :end, class: end_class, placeholder: "Enter end" %>
    <% if end_was_invalid %>
      <% event.errors.full_messages_for(:end).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% address_class = "form-control" %>
    <% address_was_invalid = event.errors.include?(:address) %>

    <% if was_validated %>
      <% if address_was_invalid %>
        <% address_class << " is-invalid" %>
      <% else %>
        <% address_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :address %>
    <%= f.text_field :address, class: address_class, placeholder: "Enter address" %>
    <% if address_was_invalid %>
      <% event.errors.full_messages_for(:address).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% detail_class = "form-control" %>
    <% detail_was_invalid = event.errors.include?(:detail) %>

    <% if was_validated %>
      <% if detail_was_invalid %>
        <% detail_class << " is-invalid" %>
      <% else %>
        <% detail_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :details %>
    <%= f.text_area :details, class: detail_class, placeholder: "Enter detail" %>
    <% if detail_was_invalid %>
      <% event.errors.full_messages_for(:detail).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% photo_class = "form-control" %>
    <% photo_was_invalid = event.errors.include?(:photo) %>

    <% if was_validated %>
      <% if photo_was_invalid %>
        <% photo_class << " is-invalid" %>
      <% else %>
        <% photo_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :photo %>
    <%= f.file_field :photo, class: "form-control" %>
    <% if photo_was_invalid %>
      <% event.errors.full_messages_for(:photo).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/events/_list_item.html.erb
<%= link_to event, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= event %>
    <small class="text-muted">
      <%= time_ago_in_words(event.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/events/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Event #<%= @event.id %>
      </h2>

      <div class="card-body">
        <%= render "form", event: @event %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Events

      <%= link_to new_event_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "events/events_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Events

        <%= link_to new_event_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @events, partial: "list_item", as: :event %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @events, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Event
      </h2>

      <div class="card-body">
        <%= render "form", event: @event %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @event, partial: "card", as: :event %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "events/event_comments" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "events/event_attendees" %>
  </div>
</div>